apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: whitelists.police.k8s.io
spec:
  group: police.k8s.io
  names:
    kind: WhiteList
    plural: whitelists
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            images:
              items:
                properties:
                  name:
                    type: string
                  tags:
                    items:
                      type: string
                    type: array
                required:
                - name
                - tags
                type: object
              type: array
          required:
          - images
          type: object
        status:
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
